### ISSUE TITLE
Doesn't work with latest Elasticsearch 6

### ISSUE THREAD

**Issue by bmunkholm** [torkelo/github-to-es#2]
@torkelo 
Due to breaking change: https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html
this error occurs:

````
node app.js init | bunyan                                                                                                                                                                            
[2018-03-04T21:13:28.524Z]  INFO: RepoSync/83623 on zzz: github_token xxxxx
[2018-03-04T21:13:28.529Z]  INFO: app/83623 on zzz: creating index
[2018-03-04T21:13:28.672Z] ERROR: app/83623 on zzz: index creation failed
    Error: [illegal_argument_exception] Rejecting mapping update to [github] as the final mapping would have more than 1 type: [issue, comment]
        at respond (/Users/bm/github-to-es/node_modules/elasticsearch/src/lib/transport.js:307:15)
        at checkRespForFailure (/Users/bm/github-to-es/node_modules/elasticsearch/src/lib/transport.js:266:7)
        at HttpConnector.<anonymous> (/Users/bm/github-to-es/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
        at IncomingMessage.bound (/Users/bm/github-to-es/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1056:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
````

**Comment by wolfohyeah** [comment]
Hi, I got None of `preview of values` in the variables query. [issue](https://github.com/grafana/grafana/issues/8765#issuecomment-347386428)

**Comment by eduardohki** [comment]
Definitely this would be really nice to have in Grafana :)
